name: Deploy Streamlit App

on:
  push:
    branches:
      - master  # Change this to your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # or your preferred version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Restart Streamlit app
        run: |
          pkill -f streamlitapp.py || true  # Kill any previous instance (if running)
          nohup streamlit run streamlitapp.py &  # Restart the app in the background
